import { type NextPage } from "next";
import Head from "next/head";
import NavBar from "~/components/NavBar"
import React from "react"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
      </main>
    </>
  );
};

export default Home
